import { QueryProvider } from "@/query-provider/query";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";


export const metadata = {
  title: "Cv",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <QueryProvider>
          <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            {children}
          </ThemeProvider>

        </QueryProvider>
      </body>
    </html>
  );
}
