import { QueryProvider } from "@/query-provider/query";
import "./globals.css";


export const metadata = {
  title: "Cv",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
